Add kibana ansible role
opsta/ansible-kibana pull request #1
Opened 2019-01-07 07:06 UTC by pongsakm2007

2019-01-07 07:26 UTC, winggundamth requested changes
Please check comment

2019-01-07 07:26 UTC, winggundamth commented on handlers/main.yml
> +  service: name=kibana state=restarted
Please use our convention

```
  service:
    name: kibana
    state: restarted
```

2019-01-07 07:26 UTC, winggundamth commented on meta/.galaxy_install_info
> +{install_date: 'Fri Jan  4 04:19:43 2019', version: master}
I think this file should be removed

2019-01-07 07:26 UTC, winggundamth commented on tasks/kibana_pre.yml
> +  apt: name=apt-transport-https state=present
Use our convention

```
  apt:
    name: apt-transport-https
    state: present
```

2019-01-07 07:26 UTC, winggundamth commented on tasks/kibana_pre.yml
> +    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
We should use "deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main" as variable in defaults/main.yml

2019-01-07 07:26 UTC, winggundamth commented on tasks/kibana_pre.yml
> +    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
We should use "https://artifacts.elastic.co/GPG-KEY-elasticsearch" as variable in defaults/main.yml

2019-01-07 07:26 UTC, winggundamth commented on tasks/main.yml
> +    - "{{ ansible_os_family }}.yml"
Not sure if we don't have specific OS variable. Should we remove this and remove vars/Debian.yml as well

2019-01-07 07:26 UTC, winggundamth commented on tasks/kibana_search_config.yml
> +- debug: var=kibana_config_check
Remove debug

2019-01-07 07:26 UTC, winggundamth commented on LICENSE
> +Copyright (c) 2017 Opsta
Copyright (c) 2019 Opsta

2019-01-07 07:35 UTC, pongsakm2007 commented on handlers/main.yml
> +  service: name=kibana state=restarted
Done krub

2019-01-07 07:35 UTC, pongsakm2007 commented on tasks/kibana_pre.yml
> +  apt: name=apt-transport-https state=present
Done krub

2019-01-07 07:35 UTC, pongsakm2007 commented on tasks/kibana_pre.yml
> +    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
Done krub

2019-01-07 07:36 UTC, pongsakm2007 commented on meta/.galaxy_install_info
> +{install_date: 'Fri Jan  4 04:19:43 2019', version: master}
Done krub

2019-01-07 07:36 UTC, pongsakm2007 commented on tasks/kibana_pre.yml
> +    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
Done krub

2019-01-07 07:38 UTC, pongsakm2007 commented on tasks/main.yml
> +    - "{{ ansible_os_family }}.yml"
Done krub

2019-01-07 07:40 UTC, pongsakm2007 commented on tasks/kibana_search_config.yml
> +- debug: var=kibana_config_check
Done krub

2019-01-07 07:40 UTC, pongsakm2007 commented on LICENSE
> +Copyright (c) 2017 Opsta
Done krub

2019-01-08 06:34 UTC, winggundamth approved these changes
LGTM

2019-01-08 06:34 UTC, merged